#mongodb
server.port=8989
spring.data.mongodb.host=amitmangal.com
spring.data.mongodb.port=27017
spring.data.mongodb.database=tradebot




logging.level.root=INFO
logging.level.com.example.mongo=DEBUG
logging.file.name=Logs/application.log


# Enable MongoDB logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.convert.MappingMongoConverter=DEBUG
logging.level.org.mongodb.driver=INFO
