#mongodb
server.port=8989
spring.data.mongodb.host=amitmangal.com
spring.data.mongodb.port=27017
spring.data.mongodb.database=tradebot
spring.data.mongodb.username=tradeBotU
spring.data.mongodb.password=Amit2648
spring.data.mongodb.auto-index-creation=true



logging.level.root=INFO
logging.level.com.example.mongo=DEBUG
logging.file.name=Logs/application.log


# Enable MongoDB logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.convert.MappingMongoConverter=DEBUG
logging.level.org.mongodb.driver=INFO

upstocAccessToken=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyNENZUDUiLCJqdGkiOiI2OTViZjFkZWRkODdjNzNmOGVhNTE5OWYiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzY3NjMzMzc0LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NzAxNTYwMDB9.zoyLExT6tUNXao9bttN69w63kVcSWtQ-7ULMGy1G7BI